LOCALHOST_ADDRESS = '127.0.0.1'
MIN_PORT = 1024
MAX_PORT = 65535
CLIENT_NAME_PACKET_SIZE = 1024
CLIENT_ANSWER_PACKET_SIZE = 1

BROADCAST_ADDRESS = '<broadcast>'
BROADCAST_PORT = 13117
BROADCAST_MAGIC_COOKIE = 0xabcddcba
BROADCAST_MESSAGE_TYPE = 0x2

CLIENT_NAME_TERMINATION = '\n'
CLIENT_NO_JOIN_TIMEOUT_SEC = 10

SERVER_NAME = 'NovaBeach'
SERVER_NO_ANSWER_TIMEOUT_SEC = 10
SERVER_BROADCAST_PERIOD_SEC = 1
SERVER_POST_WELCOME_PAUSE_SEC = 2
TRUE_ANSWERS = ['Y', 'T', '1']
FALSE_ANSWERS = ['N', 'F', '0']

# message types
WELCOME_MESSAGE = '[W]'
ERROR_MESSAGE = '[E]'
QUESTION_MESSAGE = '[Q]'
BYE_MESSAGE = '[B]'
GAME_OVER_MESSAGE = '[GO]'
