CLIENT_NAME_TERMINATION = '\n'
CLIENT_NO_JOIN_TIMEOUT_SEC = 10

BROADCAST_PORT = 13117
SERVER_IP_ADDRESS = '127.0.0.1'
SERVER_NO_ANSWER_TIMEOUT_SEC = 10
SERVER_BROADCAST_PERIOD_SEC = 1
TRUE_ANSWERS = ['Y', 'T', '1']
FALSE_ANSWERS = ['N', 'F', '0']
