QUESTIONS = [
    ("The Great Wall of China is visible from space.", False),
    ("Bananas grow on trees.", False),
    ("Alexander Graham Bell invented the telephone.", True),
    ("The Earth is the only planet in the solar system with liquid water on its surface.", True),
    ("Napoleon Bonaparte was extremely tall for his time.", False),
    ("The Mona Lisa has no eyebrows.", True),
    ("All polar bears are left-handed.", False),
    ("Marie Curie was the first woman to win a Nobel Prize.", True),
    ("Dolphins sleep with one eye open.", True),
    ("The Great Barrier Reef is the largest living structure on Earth.", True),
    ("Mount Everest is the tallest mountain in the world.", True),
    ("Goldfish have a three-second memory.", False),
    ("Bees die after they sting someone.", True),
    ("The capital of Australia is Sydney.", False),
    ("Neil Armstrong was the first person to walk on the moon.", True),
    ("The human body has 206 bones.", True),
    ("Cleopatra was Egyptian.", True),
    ("The Eiffel Tower was originally intended to be a temporary structure.", True),
    ("The Amazon Rainforest produces 20% of the world's oxygen.", True),
    ("Sharks are mammals.", False),
    ("The platypus lays eggs.", True),
    ("Albert Einstein failed math in school.", False),
    ("Chameleons change color to blend in with their surroundings.", False),
    ("The Sahara Desert is the largest desert in the world.", False),
    ("Bruce Lee was the founder of Jeet Kune Do.", True),
    ("The Statue of Liberty was a gift from France to the United States.", True),
    ("Elephants are afraid of mice.", False),
    ("Thomas Edison invented the light bulb.", True),
    ("The Nile River is the longest river in the world.", False),
    ("Cats have fewer teeth than dogs.", True),
    ("Diamonds are made from compressed coal.", False),
    ("The Leaning Tower of Pisa is located in Italy.", True),
    ("Julius Caesar was assassinated on the steps of the Roman Senate.", True),
    ("Penguins can fly.", False),
    ("Vincent van Gogh only sold one painting during his lifetime.", True),
    ("The capital of Canada is Toronto.", False),
    ("The fastest land animal is the cheetah.", True),
    ("The human brain stops growing after the age of 25.", False),
    ("The moon is larger than the smallest planet in our solar system, Mercury.", True),
    ("The Titanic sank in 1912 after hitting an iceberg.", True),
    ("The term 'Mayday' used in distress calls comes from the French word 'm'aider,' meaning 'help me.'", True),
    ("Spiders are insects.", False),
    ("Walt Disney was cryogenically frozen after his death.", False),
    ("Hawaii is the largest state in the United States by land area.", False),
    ("The first computer virus was created in the 1970s.", True),
    ("The longest river in South America is the Amazon River.", True),
    ("The Statue of Liberty's official name is 'Liberty Enlightening the World.'", True),
    ("The longest bone in the human body is the femur.", True),
    ("George Washington had wooden teeth.", False),
    ("There are more stars in the universe than grains of sand on Earth.", True),
    ("The sun is a planet.", False),
    ("The speed of light is faster than the speed of sound.", True),
    ("Turtles can breathe through their butts.", True),
    ("The fastest fish in the ocean is the swordfish.", True),
    ("Russia is the largest country in the world by land area.", True),
    ("Chocolate contains caffeine.", True),
    ("The Earth's atmosphere is composed mostly of nitrogen.", True),
    ("The smallest bone in the human body is in the ear.", True),
    ("The Declaration of Independence was signed in 1776.", True),
    ("The largest organ in the human body is the liver.", False),
    ("Venus is the hottest planet in our solar system.", True),
    ("The term 'OK' stands for 'Oll Korrect.'", True),
    ("The United States has never had a female president.", True),
    ("The human heart pumps blood continuously throughout one's lifetime.", True),
    ("The famous 'I Have a Dream' speech was delivered by Martin Luther King Jr. in 1963.", True),
    ("The human body has more than 600 muscles.", True),
    ("Venus is the closest planet to Earth.", True),
    ("The fastest bird is the peregrine falcon.", True),
    ("Jupiter has the most moons in our solar system.", True),
    ("The Great Wall of China is the longest man-made structure in the world.", True),
    ("The Berlin Wall fell in 1989.", True),
    ("Water boils at a higher temperature at higher altitudes.", False),
    ("The first human to travel into space was Yuri Gagarin.", True),
    ("The human body can survive longer without food than without water.", True),
    ("William Shakespeare was born in the 16th century.", True),
    ("Antarctica is the coldest continent on Earth.", True),
    ("The first computer mouse was made of wood.", True),
    ("The moon has its own magnetic field.", False),
    ("The largest volcano in the solar system is Olympus Mons on Mars.", True),
    ("A group of flamingos is called a flamboyance.", True),
    ("The fastest land animal is the ostrich.", False),
    ("The human nose can remember 50,000 different scents.", True),
    ("The largest ocean on Earth is the Pacific Ocean.", True),
    ("The capital of Brazil is Rio de Janeiro.", False),
    ("The first person to circumnavigate the globe was Ferdinand Magellan.", True),
    ("The human body has more than 200 different types of cells.", True),
    ("The koala is not a bear.", True),
    ("There are 24 time zones in the world.", True),
    ("All snowflakes have six sides.", False),
    ("Beethoven was completely deaf when he composed his famous Ninth Symphony.", True),
    ("A group of crows is called a murder.", True),
    ("The human body has four kidneys.", False),
    ("The Mediterranean Sea is the largest sea in the world.", False),
    ("The Sahara Desert expands by about 6 feet every year.", False),
    ("The longest recorded flight of a chicken is 13 seconds.", False),
    ("The shortest war in history lasted only 38 minutes.", True),
    ("The Canary Islands are named after birds.", True),
    ("Watermelon is both a fruit and a vegetable.", True),
    ("There are more than 500 species of sharks in the world.", True)
]
